# Generated by Django 4.0.4 on 2022-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music',
            field=models.FileField(null=True, upload_to='music/'),
        ),
    ]
